---
title: "QTM 150 Project"
output: html_document
date: "`r Sys.Date()`"
---
## Setup (PUT ALL YOUR LIBRARY COMMANDS FOR PACKAGES IN HERE)
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggrepel)


```

## Work

```{r pressure, echo=FALSE}
#this is a dot plot of population density of places
agri_data <- read.csv("US_Counties_Agriculture_Census_(USDA).csv")

edited_agri_data <- agri_data %>%
  mutate(percent_land_fert = (CroplandAcr / atlas_acre) * 100,
         highlight = percent_land_fert > 75) %>%
  filter(percent_land_fert > 70)

top30 <- edited_agri_data %>%
  arrange(desc(percent_land_fert)) %>%
  slice(1:30)


#g1 <-put this in front when all is done
ggplot(edited_agri_data, aes(x = atlas_caps, y = percent_land_fert)) +
  geom_point() +
  labs(
    title = "Counties with greatest percent farm land",
    x = "Names of Counties",
    y = "% farm land of county",
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    ) +
  geom_segment(
    data = top30,
    aes(
      x = atlas_caps,
      xend = atlas_caps,
      y = percent_land_fert + max(percent_land_fert) * 0.05,
      yend = percent_land_fert
    ),
    arrow = arrow(length = unit(0.15, "cm")),
    linewidth = 0.3,
    color = "red") + 
  geom_text_repel(
      data = top30,
      aes(x = atlas_caps, y = percent_land_fert + 0.06 * max(percent_land_fert), 
          label = atlas_caps),
      color = "black",
      size = 2.8,
      angle = 45,
      hjust = 0,
      segment.color = NA
    )
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
